* Introduction

  This is intended to be a sort of minimal emacs starter kit for people
  who tend to use some combination of R, LaTeX, and/or markdown. I
  wrote this because I got tired of saying something along the lines
  of: "No, I don't use Rstudio. I use emacs, but it's kind of a pain
  to get set up..."

  No more. Now that I've written this I can shamelessly recommend it
  to people.  

  This is designed to be a /very/ minimalistic configuration for emacs.
  It's nowhere near as complicated as [[https://github.com/jabranham/emacs][my own personal emacs config
  file]]. In fact, the whole =init.el= file (more on that in a bit) is
  only 85 lines long. In contrast, my =init.el= is about 2,000 lines
  long.

  So this should get people the absolute bare minimum needed to get
  started using R/latex/markdown/rmarkdown/sweave/knitr in emacs.

  As far as I know, this works on all versions of emacs greater than
  24 across Linux, Mac, and Windows operating systems. 

* First Steps

  The first thing that I would do is to go through the emacs tutorial
  just to get used to the emacs way of doing things. You can access
  the tutorial by pressing =C-h t= (that's "press =control= and hold,
  press =h=. Release both of those, then press =t="). The tutorial
  explains the most basic functions like moving around and what a
  buffer is. 

* Next Steps
  
  There are so many places to go from here! 
** references
   One of the best things I did was to set up the =org-ref= (and
   =helm-bibtex=) package. This gives me a consistent way to manage
   references, notes, and the like across latex, markdown, and
   org-mode
